---
title: "Interactive Data Viz with Quarto"
author:
  - name: "Charlotte Hadley"
date-as-string: "23 April 2026"
format: 
    visibledata-slides-revealjs:
        title-slide: false
        slide-number: "c/t"
        brand: brand.yml
---

# This template defaults to vertical

:::: {.columns}

::: {.column width="70%"}

See docs on the [quarto website](https://quarto.org/docs/presentations/revealjs/advanced.html#vertical-slides)

- Use level 1 headings to go across

- Use level 2 headings to go up/down.

We use some weirdness to make this work for us.

:::

::: {.column width="30%"}

<span style='color:{{<brand color story-primary>}};font-size:10rem'><i class="fa-solid fa-arrow-down"></i></span>


:::

::::

## Hello from up there!

:::: {.columns}

::: {.column width="70%"}

Level 2 headings create nice slides like this with the title at the top of the slide.

Head **down** to a task slide!

:::

::: {.column width="30%"}

<span style='color:{{<brand color story-primary>}};font-size:10rem'><i class="fa-solid fa-arrow-down"></i></span>

:::

::::

## Task slide

::: {.task-icon}
<i class="fa-solid fa-clipboard-question"></i>
:::


:::: {.columns}

::: {.column width="70%"}

Level 2 headings create nice slides like this with the title at the top of the slide.

Head **across** to the next section of the talk!

:::

::: {.column width="30%"}

<span style='color:{{<brand color story-primary>}};font-size:10rem'><i class="fa-solid fa-arrow-down"></i></span>

:::

::::

## References

::: {.card-attribution}
DOI: [10.1080/17457289.2018.1465061](https://10.1080/17457289.2018.1465061)

Year: 2019
:::

## Quotes!

<blockquote class="quote-graph">
We use blockquote to support accessibility tools
</blockquote>


<blockquote class="quote-plot">
If we styled a div it would lose meaning
</blockquote>


<blockquote class="quote-chart">
Note that we use dark colours
</blockquote>

<blockquote class="quote-story">
For contrast accessibility
</blockquote>

<blockquote class="quote-story-alt">
But provide a 'quote-story-alt' for emphasis.
</blockquote>


# Section break slides {.graph-title-slide .fa-down-arrow}

These indicate you should go downwards.

::: {.section-arrow}
<i class="fa-solid fa-arrow-down"></i>
:::

## Visible Data slide styles {.story-slide}

Notice how everything looks a little different? Well, there are these special classes:

- .graph-slide
- .graph-title-slide
- .plot-slide
- .plot-title-slide
- .chart-slide
- .chart-title-slide
- .story-slide
- .story-title-slide

# Default section break

Notice there is no arrow here.

The arrow was added using 

```{verbatim}
::: {.section-arrow}
<i class="fa-solid fa-arrow-down"></i>
:::
```


# Another nice section break {.story-title-slide}

# 

### 1-3, miss the 2

:::: {.columns}

::: {.column width="70%"}

Using this pattern creates across slides that feel like normal progression.

```{verbatim}
#

### 1-3, miss the 2
```

However it is recommended to **AVOID THIS** as it has very non-standard behaviour. Check the source to see terrifying things done to the `<section>` tags.

:::

::: {.column width="30%"}

<span style='color:{{<brand color story-primary>}};font-size:10rem'><i class="fa-solid fa-bomb"></i></span>

:::

::::

# Task slide

::: {.task-icon}
<i class="fa-solid fa-clipboard-question"></i>
:::

```{r}
2 + 2
```


